services:
  # Our database management system
  db:
    environment:
      environment:
      MARIADB_USER: &dbuser todo
      MARIADB_PASSWORD: &dbpass todosecret
      MARIADB_ROOT_PASSWORD: iamroot
      MARIADB_DATABASE: &dbname db
      
  videos:
    environment:
      DB_USER: *dbuser
      DB_PASSWORD: *dbpass
      DB_NAME: *dbname
  
  subscriptions:
    environment:
      DB_USER: *dbuser
      DB_PASSWORD: *dbpass
      DB_NAME: *dbname